/* Generated By:JavaCC: Do not edit this line. FtpParserConstants.java */
/*
 * Copyright (C) 2011 Marco Ratto
 *
 * This file is part of the project ftp-client-java.
 *
 * ftp-client-java is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * any later version.
 *
 * ftp-client-java is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ftp-client-java; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
package uk.co.marcoratto.ftp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FtpParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 3;
  /** RegularExpression Id. */
  int CRLF = 4;
  /** RegularExpression Id. */
  int HELP = 5;
  /** RegularExpression Id. */
  int BANG = 6;
  /** RegularExpression Id. */
  int CD = 7;
  /** RegularExpression Id. */
  int LCD = 8;
  /** RegularExpression Id. */
  int LS = 9;
  /** RegularExpression Id. */
  int QC = 10;
  /** RegularExpression Id. */
  int QUIT = 11;
  /** RegularExpression Id. */
  int MKDIR = 12;
  /** RegularExpression Id. */
  int RMDIR = 13;
  /** RegularExpression Id. */
  int PUT = 14;
  /** RegularExpression Id. */
  int DELETE = 15;
  /** RegularExpression Id. */
  int MPUT = 16;
  /** RegularExpression Id. */
  int GET = 17;
  /** RegularExpression Id. */
  int MGET = 18;
  /** RegularExpression Id. */
  int RENAME = 19;
  /** RegularExpression Id. */
  int SIZE = 20;
  /** RegularExpression Id. */
  int NLIST = 21;
  /** RegularExpression Id. */
  int USER = 22;
  /** RegularExpression Id. */
  int PASSIVE = 23;
  /** RegularExpression Id. */
  int PROMPT = 24;
  /** RegularExpression Id. */
  int HASH = 25;
  /** RegularExpression Id. */
  int BINARY = 26;
  /** RegularExpression Id. */
  int ASCII = 27;
  /** RegularExpression Id. */
  int VERBOSE = 28;
  /** RegularExpression Id. */
  int DEBUG = 29;
  /** RegularExpression Id. */
  int OPEN = 30;
  /** RegularExpression Id. */
  int CLOSE = 31;
  /** RegularExpression Id. */
  int TYPE = 32;
  /** RegularExpression Id. */
  int PWD = 33;
  /** RegularExpression Id. */
  int RHELP = 34;
  /** RegularExpression Id. */
  int SYSTEM = 35;
  /** RegularExpression Id. */
  int RNFR = 36;
  /** RegularExpression Id. */
  int STRING = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"\\n\"",
    "<HELP>",
    "\"!\"",
    "\"CD\"",
    "\"LCD\"",
    "<LS>",
    "\"QC\"",
    "<QUIT>",
    "<MKDIR>",
    "<RMDIR>",
    "<PUT>",
    "<DELETE>",
    "<MPUT>",
    "<GET>",
    "<MGET>",
    "<RENAME>",
    "<SIZE>",
    "<NLIST>",
    "<USER>",
    "<PASSIVE>",
    "<PROMPT>",
    "<HASH>",
    "<BINARY>",
    "<ASCII>",
    "<VERBOSE>",
    "<DEBUG>",
    "<OPEN>",
    "<CLOSE>",
    "<TYPE>",
    "<PWD>",
    "<RHELP>",
    "<SYSTEM>",
    "\"RNFR\"",
    "<STRING>",
    "\";\"",
  };

}
